#服务名称
spring:
  application:
    name: micr-dataservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/licai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: "000"

#redis
  redis:
    host: localhost
    port: 6379

#dubbo
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.licai.service
  provider:
    timeout: 5000
  protocol:
    name: dubbo



#mybatis
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.bjpowernode.licai.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#指定日志的配置文件
logging:
  config: classpath:logback-spring.xml
